### ISSUE TITLE
instantiating non-existent module

### ISSUE THREAD

**Issue by efeamadasun** [wilhelma/parceive-ui#16]
Let's say you have a view in the parcieve code (which is an angular module, call it "profile-view"), and then you run the app on your browser, and add that view to the page, so it displays. And then you go to the code and delete the "profile-view" module, and then refresh your browser, you will get this error. 

![error](https://cloud.githubusercontent.com/assets/809644/9436469/d1f45a68-4a4f-11e5-9e78-e1c0fa90db28.png)

I believe this is because when you added the view to the page earlier, it got saved to the browser's localStorage, and when you refreshed, it tried to load the views in localStorage, which included the now non-existent "profile-view" module. 

Clearing the browser's localStorage fixes this problem.

**Comment by victorsavu3** [comment]
If a view is not present in the code, but it is referenced in the state, a dialog now asks if it should be removed.
